In [6]:
import pandas as pd
import requests as req 
import json 
import sys

import warnings
warnings.filterwarnings('ignore')

books_db = pd.read_csv('books.csv') # converting out data into a dataframe 

#this function output a random sample from our database

def lucky_output(start_search):
    
    if start_search == 'Lucky':
        sample = books_db.sample(10)
    return(sample)
  
genre_list = books_db['Genre'].tolist() #converting the Genre column of our program into a list 

# this function prints out unique values in our Genre column so no Genre repeats
def unique(genre_list):
    list_set = set(genre_list)
    unique_list = list(list_set)
    for x in unique_list:
        print(x, end=',')

# this function ensures that when the user types in a genre, it's a genre from the genre column
def genre(genre_pref):
    genre = books_db['Genre']== genre_pref
    genre_db = books_db[genre]
    genre_db

start_search = str(input("\n Enter Lucky or Custom:")).title()

if start_search == "Lucky":
    lucky_output(start_search)
    sys.exit(lucky_output(start_search)) # if the user enters Lucky the program ends and gives a sample from data
      
elif start_search == "Custom":
    print(unique(genre_list)) # prints out list of genre's so the user knows what to choose from
else:
    sys.exit("Invalid Entry enter Lucky or Custom.")
    
    
genre_pref = str(input("\n Enter Your Favorite Genre From The List of Genres:")).title()
genre = books_db['Genre']== genre_pref   # genre entered is equalivant to the genre in books database
genre_db = books_db[genre]

#if genre_pref != genre_db[genre_db["Genre"]]: 
    #sys.exit('Not in Genre list')
    
#RATING is calling from genre database 

try:
    rate_pref = int(input("On a scale of 1-4, how important is the rate of the book? (1 being low importance, 4 being high importance): "))   
except ValueError:
    print("Enter integers only")
    
try:
    if rate_pref==1: 
        rate_db = genre_db

    elif rate_pref==2:
        rate_db = genre_db[ genre_db['Rating']>=2.0]

    elif rate_pref==3:
        rate_db = genre_db[ genre_db['Rating']>=3.0]

    elif rate_pref==4:
        rate_db = genre_db[ genre_db['Rating']>=4.3]

    else: 
        print('Invalid Entry \n')

except NameError:
    print('Program will not work at intended until a numeric value!')


# PAGES 

try:
    pages_pref = int(input("On a 1-4 scale, rate how long you would like the book to be: \n"))
except ValueError:
    print("Enter integers only")

try:
    if pages_pref==1:
        pages_db = rate_db

    elif pages_pref==2:
        pages_db = rate_db[ rate_db['PAges']> 200]

    elif pages_pref==3:
        pages_db = rate_db.query('200 <= PAges <= 400')

    elif pages_pref==4:
        pages_db = rate_db[ rate_db['PAges']> 400]

    else: 
        print('Invalid Entry')
except NameError:
    print("Program will not work as intended until you enter a numeric value!")

    
#YEAR

try:
    year_pref = int(input("On a scale of 1-4, rate how old or new you would like the book to be: "))
except ValueError:
    print("Enter integers only \n")
    
try:
    if year_pref==1:
        year_db = pages_db

    elif year_pref==2:
        year_db = pages_db.query('1800 <= Year <= 1920')

    elif year_pref==3:
        year_db = pages_db.query('1921 <= Year <= 1990')

    elif year_pref==4:
        year_db = pages_db[ pages_db['Year']>1990] 
except NameError:
    print("Program will not work as intended until you enter a numeric value!")

year_db.head(10)

 Enter Lucky or Custom:custom
History,Science,LGBTQ,Anime ,Paranormal,Poetry,Fantasy,Art,Spirituality ,Crime,Psychology,Graphic Novels,Science Fiction,Chick Lit,Business,Classic,Cookbooks,Manga,Travel,Biography,Children,Sports,Romance,Nonfiction,Fiction,Young Adult,Contemporary,Horror,Philosophy,Memoir,Religion,Historical Fiction,Self Help,Thriller,Comics,Music,Mystery,Ebooks,Suspense,None

 Enter Your Favorite Genre From The List of Genres:history
On a scale of 1-4, how important is the rate of the book? (1 being low importance, 4 being high importance): 1
On a 1-4 scale, rate how long you would like the book to be:
3
On a scale of 1-4, rate how old or new you would like the book to be: 4

,Title,Author,Genre,PAges,Rating,Publisher,Year
3876,The Disappearing Spoon: And Other True Tales o...,Sam Kean,History,394.0,3.91,"Little, Brown and Company",2010.0
3877,A Night to Remember,Walter Lord,History,208.0,4.02,Holt McDougal,2005.0
3880,The New Jim Crow: Mass Incarceration in the Ag...,Michelle Alexander,History,290.0,4.52,The New Press,2010.0
3881,"The Age of Revolution, 1789-1848",Eric Hobsbawm,History,368.0,4.18,Vintage,1996.0
3882,"Lost in Shangri-la: A True Story of Survival, ...",Mitchell Zuckoff,History,384.0,3.85,HarperCollins Publishers (NYC),2011.0
3885,The Age of Wonder: How the Romantic Generation...,Richard Holmes,History,380.0,3.95,HarperPress,2009.0
3888,Ordinary Men: Reserve Police Battalion 101 and...,Christopher R. Browning,History,271.0,4.08,Harper Perennial,1993.0
3895,Killing Kennedy: The End of Camelot (The Killi...,Bill O'Reilly,History,325.0,4.07,Henry Holt and Co.,2012.0
3896,Ghost Soldiers: The Epic Account of World War ...,Hampton Sides,History,344.0,4.20,Anchor,2002.0
3898,Cod: A Biography of the Fish that Changed the ...,Mark Kurlansky,History,294.0,3.90,Vintage/Ebury,1999.0

In [4]:
start_search = input("en")
lucky_output(start_search)

enLucky

,Title,Author,Genre,PAges,Rating,Publisher,Year
5396,How Proust Can Change Your Life,Alain de Botton,Philosophy,208.0,3.76,Vintage,1998.0
2014,"Transmetropolitan, Vol. 3: Year of the Bastard",Warren Ellis,Comics,144.0,4.40,Vertigo,1999.0
3148,"Blue Lily, Lily Blue (The Raven Cycle, #3)",Maggie Stiefvater,LGBTQ,391.0,4.31,Scholastic Press,2014.0
6919,The 7 Habits of Highly Effective People: Power...,Stephen R. Covey,Self Help,372.0,4.08,Free Press,2004.0
403,"Lord of Scoundrels (Scoundrels, #3)",Loretta Chase,Romance,375.0,4.11,Avon Books,1995.0
1027,Founders at Work: Stories of Startups' Early Days,Jessica Livingston,Business,456.0,3.93,Apress,2007.0
4942,An Astronaut's Guide to Life on Earth,Chris Hadfield,Nonfiction,295.0,4.17,"Little, Brown and Company",2013.0
7657,"The Enemy (Jack Reacher, #8)",Lee Child,Thriller,464.0,4.17,Dell Publishing Company,2005.0
4498,Furiously Happy: A Funny Book About Horrible T...,Jenny Lawson,Memoir,329.0,3.93,Flatiron Books,2015.0
3924,In Cold Blood,Truman Capote,History,343.0,4.07,Vintage,1994.0

In [ ]:
Questions to ask during office hours

# why upper is not working? 
# if genre_pref is not eqal to  a genre in database how do I write this 
#